use alloc::{boxed::Box, collections::btree_map::BTreeMap, sync::Arc, task::Wake};
use core::{
    future::Future,
    pin::Pin,
    sync::atomic::{AtomicU64, Ordering},
    task::{Context, Poll, Waker},
};

use crossbeam_queue::ArrayQueue;

use crate::intr::{disable_interrupt, enable_interrupt, wait_for_interrupt};

pub struct Task {
    id:      TaskId,
    // NOTE: features generated by async/await maybe self reference,
    // so we need to use pin to make it fixed in heap.
    feature: Pin<Box<dyn Future<Output = ()>>>,
}

impl Task {
    // 'static means the feature must be existed before the returned
    // Task is dropped.
    pub fn new(feature: impl Future<Output = ()> + 'static) -> Task {
        Task {
            id:      TaskId::new(),
            feature: Box::pin(feature),
        }
    }

    pub fn poll(&mut self, cx: &mut Context) -> Poll<()> {
        self.feature.as_mut().poll(cx)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct TaskId(u64);

impl TaskId {
    fn new() -> TaskId {
        static NEXT_ID: AtomicU64 = AtomicU64::new(0);
        TaskId(NEXT_ID.fetch_add(1, Ordering::Relaxed))
    }
}

pub struct Executor {
    tasks:       BTreeMap<TaskId, Task>,
    // task_queue will be shared between executor and waker
    task_queue:  Arc<ArrayQueue<TaskId>>,
    waker_cache: BTreeMap<TaskId, Waker>,
}

impl Executor {
    pub fn new() -> Self {
        Executor {
            tasks:       BTreeMap::new(),
            task_queue:  Arc::new(ArrayQueue::new(100)),
            waker_cache: BTreeMap::new(),
        }
    }

    pub fn spawn(&mut self, task: Task) {
        let task_id = task.id;
        if self.tasks.insert(task_id, task).is_some() {
            panic!("task with same ID already in tasks");
        }
        self.task_queue.push(task_id).expect("queue full");
    }

    fn run_ready_tasks(&mut self) {
        while let Some(task_id) = self.task_queue.pop() {
            let task = match self.tasks.get_mut(&task_id) {
                Some(task) => task,
                None => continue, // task no longer exists
            };
            let waker = self
                .waker_cache
                .entry(task_id)
                .or_insert_with(|| TaskWaker::new(task_id, self.task_queue.clone()));
            let mut context = Context::from_waker(waker);
            match task.poll(&mut context) {
                Poll::Ready(()) => {
                    // task done -> remove it and its cached waker
                    self.tasks.remove(&task_id);
                    self.waker_cache.remove(&task_id);
                }
                Poll::Pending => {}
            }
        }
    }

    pub fn run(&mut self) -> ! {
        loop {
            self.run_ready_tasks();
            self.sleep_if_idle();
        }
    }

    fn sleep_if_idle(&self) {
        unsafe {
            disable_interrupt();
            if self.task_queue.is_empty() {
                wait_for_interrupt();
            } else {
                enable_interrupt();
            }
        }
    }
}

struct TaskWaker {
    task_id:    TaskId,
    task_queue: Arc<ArrayQueue<TaskId>>,
}

impl TaskWaker {
    fn new(task_id: TaskId, task_queue: Arc<ArrayQueue<TaskId>>) -> Waker {
        Waker::from(Arc::new(TaskWaker {
            task_id,
            task_queue,
        }))
    }

    fn wake_task(&self) {
        self.task_queue.push(self.task_id).expect("task_queue full");
    }
}

impl Wake for TaskWaker {
    fn wake(self: Arc<Self>) {
        self.wake_task();
    }

    fn wake_by_ref(self: &Arc<Self>) {
        self.wake_task();
    }
}
